// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AutoRepair(arg1:string):Promise<main.ServiceStatus>;

export function CheckGoogleAuth():Promise<main.GoogleAuthStatus>;

export function CheckHealth():Promise<main.HealthReport>;

export function ClaimTask(arg1:string,arg2:string):Promise<main.Task>;

export function ClearChatHistory(arg1:string):Promise<void>;

export function CreateBusinessUnit(arg1:main.BusinessUnit):Promise<main.BusinessUnit>;

export function CreateChatSession(arg1:string,arg2:string):Promise<main.ChatSessionInfo>;

export function CreateClient(arg1:main.Client):Promise<main.Client>;

export function CreateEvent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.CreateEventResult>;

export function CreateProject(arg1:main.Project):Promise<main.Project>;

export function CreateTask(arg1:main.Task):Promise<main.Task>;

export function DeleteBusinessUnit(arg1:string):Promise<void>;

export function DeleteClient(arg1:string):Promise<void>;

export function DeleteEvent(arg1:string):Promise<main.DeleteEventResult>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<boolean>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetBusinessUnits(arg1:string):Promise<Array<main.BusinessUnit>>;

export function GetChatHistory(arg1:string):Promise<Array<main.ChatMessage>>;

export function GetClient(arg1:string):Promise<main.Client>;

export function GetClients():Promise<Array<main.Client>>;

export function GetEmail(arg1:string):Promise<main.EmailDetailResult>;

export function GetEmails(arg1:number):Promise<main.EmailResult>;

export function GetGoogleUserInfo():Promise<main.GoogleUserInfo>;

export function GetIdeas():Promise<Array<main.Idea>>;

export function GetProject(arg1:string):Promise<main.Project>;

export function GetProjectStats(arg1:string):Promise<main.ProjectStats>;

export function GetProjects(arg1:string,arg2:string):Promise<Array<main.Project>>;

export function GetTasks(arg1:string,arg2:string):Promise<Array<main.Task>>;

export function GetTodayEvents():Promise<main.CalendarResult>;

export function GetUpcomingEvents(arg1:number):Promise<main.CalendarResult>;

export function Greet(arg1:string):Promise<string>;

export function ListChatSessions():Promise<Array<main.ChatSessionInfo>>;

export function LogoutGoogle():Promise<boolean>;

export function MarkAsRead(arg1:string):Promise<main.SendEmailResult>;

export function SendEmail(arg1:string,arg2:string,arg3:string):Promise<main.SendEmailResult>;

export function StartGoogleLogin():Promise<main.GoogleAuthStatus>;

export function StreamChat(arg1:string,arg2:string):Promise<void>;

export function StreamChatWithImages(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SwitchSession(arg1:string):Promise<Array<main.ChatMessage>>;

export function UpdateBusinessUnit(arg1:main.BusinessUnit):Promise<main.BusinessUnit>;

export function UpdateClient(arg1:main.Client):Promise<main.Client>;

export function UpdateProject(arg1:main.Project):Promise<main.Project>;

export function UpdateTask(arg1:main.Task):Promise<main.Task>;
