// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddKnowledge(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.KnowledgeEntry>;

export function AddPort(arg1:string,arg2:number,arg3:string,arg4:string):Promise<main.Project>;

export function AddResearch(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.Idea>;

export function AddSuggestedTask(arg1:string,arg2:string,arg3:string):Promise<main.Idea>;

export function AutoRepair(arg1:string):Promise<main.ServiceStatus>;

export function AutoResearchIdea(arg1:string):Promise<void>;

export function CheckGoogleAuth():Promise<main.GoogleAuthStatus>;

export function CheckHandshake():Promise<main.HandshakeStatus>;

export function CheckHealth():Promise<main.HealthReport>;

export function CheckLocalRepo(arg1:string):Promise<main.ProjectLocalStatus>;

export function CheckPortConflicts(arg1:number):Promise<Array<string>>;

export function CheckPortInUse(arg1:number):Promise<boolean>;

export function ClaimTask(arg1:string,arg2:string):Promise<main.Task>;

export function ClearChatHistory(arg1:string):Promise<void>;

export function CloneRepository(arg1:string):Promise<string>;

export function ConvertIdeaToProject(arg1:string):Promise<main.Project>;

export function ConvertToGroup(arg1:string):Promise<main.Project>;

export function CreateBusinessUnit(arg1:main.BusinessUnit):Promise<main.BusinessUnit>;

export function CreateChatSession(arg1:string,arg2:string):Promise<main.ChatSessionInfo>;

export function CreateClient(arg1:main.Client):Promise<main.Client>;

export function CreateEnvFromExample(arg1:string,arg2:string):Promise<void>;

export function CreateEvent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.CreateEventResult>;

export function CreateIdea(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<main.Idea>;

export function CreateProject(arg1:main.Project):Promise<main.Project>;

export function CreateSubProject(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.Project>;

export function CreateTask(arg1:main.Task):Promise<main.Task>;

export function DeleteBusinessUnit(arg1:string):Promise<void>;

export function DeleteClient(arg1:string):Promise<void>;

export function DeleteEvent(arg1:string):Promise<main.DeleteEventResult>;

export function DeleteIdea(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<boolean>;

export function DeleteSubProject(arg1:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetActivityForEntity(arg1:string,arg2:string):Promise<Array<main.ActivityLogEntry>>;

export function GetAllGroups():Promise<Array<main.Project>>;

export function GetAllProjects():Promise<Array<main.Project>>;

export function GetAllUsedPorts():Promise<Array<main.PortWithProject>>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetBusinessUnits(arg1:string):Promise<Array<main.BusinessUnit>>;

export function GetCapabilities():Promise<string>;

export function GetCapabilitiesSummary():Promise<Record<string, any>>;

export function GetChatHistory(arg1:string):Promise<Array<main.ChatMessage>>;

export function GetClient(arg1:string):Promise<main.Client>;

export function GetClients():Promise<Array<main.Client>>;

export function GetEmail(arg1:string):Promise<main.EmailDetailResult>;

export function GetEmails(arg1:number):Promise<main.EmailResult>;

export function GetEnvFileContent(arg1:string,arg2:string):Promise<string>;

export function GetEnvVariables(arg1:string,arg2:string):Promise<Array<main.EnvVar>>;

export function GetGoogleUserInfo():Promise<main.GoogleUserInfo>;

export function GetIdea(arg1:string):Promise<main.Idea>;

export function GetIdeas(arg1:string):Promise<Array<main.Idea>>;

export function GetInstanceId():Promise<string>;

export function GetProject(arg1:string):Promise<main.Project>;

export function GetProjectStats(arg1:string):Promise<main.ProjectStats>;

export function GetProjects(arg1:string,arg2:string):Promise<Array<main.Project>>;

export function GetRecentActivity(arg1:number):Promise<Array<main.ActivityLogEntry>>;

export function GetSubProjectCount(arg1:string):Promise<number>;

export function GetSubProjects(arg1:string):Promise<Array<main.Project>>;

export function GetSyncState():Promise<main.SyncState>;

export function GetTasks(arg1:string,arg2:string):Promise<Array<main.Task>>;

export function GetTodayEvents():Promise<main.CalendarResult>;

export function GetUpcomingEvents(arg1:number):Promise<main.CalendarResult>;

export function Greet(arg1:string):Promise<string>;

export function ListChatSessions():Promise<Array<main.ChatSessionInfo>>;

export function LogActivity(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function LogoutGoogle():Promise<boolean>;

export function MarkAsRead(arg1:string):Promise<main.SendEmailResult>;

export function MoveProjectToGroup(arg1:string,arg2:string):Promise<main.Project>;

export function MoveProjectToStandalone(arg1:string):Promise<main.Project>;

export function OpenInFinder(arg1:string):Promise<void>;

export function OpenInTerminal(arg1:string):Promise<void>;

export function PerformHandshake():Promise<string>;

export function PullLatest(arg1:string):Promise<string>;

export function RemovePort(arg1:string,arg2:number):Promise<main.Project>;

export function SaveEnvFileContent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ScanEnvFiles(arg1:string):Promise<Array<main.EnvFileStatus>>;

export function SearchIdeas(arg1:string):Promise<Array<main.Idea>>;

export function SearchKnowledge(arg1:string,arg2:number):Promise<Array<main.KnowledgeSearchResult>>;

export function SendEmail(arg1:string,arg2:string,arg3:string):Promise<main.SendEmailResult>;

export function SetEnvVariable(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetLocalPath(arg1:string,arg2:string):Promise<void>;

export function StartGoogleLogin():Promise<main.GoogleAuthStatus>;

export function StartSync():Promise<void>;

export function StopSync():Promise<void>;

export function StreamChat(arg1:string,arg2:string):Promise<void>;

export function StreamChatWithImages(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SwitchSession(arg1:string):Promise<Array<main.ChatMessage>>;

export function UpdateBusinessUnit(arg1:main.BusinessUnit):Promise<main.BusinessUnit>;

export function UpdateClient(arg1:main.Client):Promise<main.Client>;

export function UpdateIdea(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:Array<string>):Promise<main.Idea>;

export function UpdateIdeaNotes(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.Idea>;

export function UpdateProject(arg1:main.Project):Promise<main.Project>;

export function UpdateSuggestedTaskStatus(arg1:string,arg2:number,arg3:string):Promise<main.Idea>;

export function UpdateTask(arg1:main.Task):Promise<main.Task>;
