// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKnowledge(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddKnowledge'](arg1, arg2, arg3, arg4, arg5);
}

export function AddPort(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddPort'](arg1, arg2, arg3, arg4);
}

export function AddResearch(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddResearch'](arg1, arg2, arg3, arg4, arg5);
}

export function AddSuggestedTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddSuggestedTask'](arg1, arg2, arg3);
}

export function AssignAgentToProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['AssignAgentToProject'](arg1, arg2, arg3);
}

export function AssignTicket(arg1, arg2) {
  return window['go']['main']['App']['AssignTicket'](arg1, arg2);
}

export function AutoRepair(arg1) {
  return window['go']['main']['App']['AutoRepair'](arg1);
}

export function AutoResearchIdea(arg1) {
  return window['go']['main']['App']['AutoResearchIdea'](arg1);
}

export function BulkUpdateTicketStatus(arg1, arg2) {
  return window['go']['main']['App']['BulkUpdateTicketStatus'](arg1, arg2);
}

export function CheckGoogleAuth() {
  return window['go']['main']['App']['CheckGoogleAuth']();
}

export function CheckHandshake() {
  return window['go']['main']['App']['CheckHandshake']();
}

export function CheckHealth() {
  return window['go']['main']['App']['CheckHealth']();
}

export function CheckLocalRepo(arg1) {
  return window['go']['main']['App']['CheckLocalRepo'](arg1);
}

export function CheckPortConflicts(arg1) {
  return window['go']['main']['App']['CheckPortConflicts'](arg1);
}

export function CheckPortInUse(arg1) {
  return window['go']['main']['App']['CheckPortInUse'](arg1);
}

export function ClaimTask(arg1, arg2) {
  return window['go']['main']['App']['ClaimTask'](arg1, arg2);
}

export function ClearChatHistory(arg1) {
  return window['go']['main']['App']['ClearChatHistory'](arg1);
}

export function CloneRepository(arg1) {
  return window['go']['main']['App']['CloneRepository'](arg1);
}

export function ConvertIdeaToProject(arg1) {
  return window['go']['main']['App']['ConvertIdeaToProject'](arg1);
}

export function ConvertToGroup(arg1) {
  return window['go']['main']['App']['ConvertToGroup'](arg1);
}

export function CreateBusinessUnit(arg1) {
  return window['go']['main']['App']['CreateBusinessUnit'](arg1);
}

export function CreateChatSession(arg1, arg2) {
  return window['go']['main']['App']['CreateChatSession'](arg1, arg2);
}

export function CreateClient(arg1) {
  return window['go']['main']['App']['CreateClient'](arg1);
}

export function CreateEnvFromExample(arg1, arg2) {
  return window['go']['main']['App']['CreateEnvFromExample'](arg1, arg2);
}

export function CreateEpic(arg1) {
  return window['go']['main']['App']['CreateEpic'](arg1);
}

export function CreateEvent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateEvent'](arg1, arg2, arg3, arg4);
}

export function CreateIdea(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateIdea'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateSubProject(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateSubProject'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function CreateTicket(arg1) {
  return window['go']['main']['App']['CreateTicket'](arg1);
}

export function DeleteAgent(arg1) {
  return window['go']['main']['App']['DeleteAgent'](arg1);
}

export function DeleteBusinessUnit(arg1) {
  return window['go']['main']['App']['DeleteBusinessUnit'](arg1);
}

export function DeleteClient(arg1) {
  return window['go']['main']['App']['DeleteClient'](arg1);
}

export function DeleteEpic(arg1) {
  return window['go']['main']['App']['DeleteEpic'](arg1);
}

export function DeleteEvent(arg1) {
  return window['go']['main']['App']['DeleteEvent'](arg1);
}

export function DeleteIdea(arg1) {
  return window['go']['main']['App']['DeleteIdea'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteSubProject(arg1) {
  return window['go']['main']['App']['DeleteSubProject'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DeleteTicket(arg1) {
  return window['go']['main']['App']['DeleteTicket'](arg1);
}

export function GenerateTickets(arg1) {
  return window['go']['main']['App']['GenerateTickets'](arg1);
}

export function GetActivityForEntity(arg1, arg2) {
  return window['go']['main']['App']['GetActivityForEntity'](arg1, arg2);
}

export function GetAgent(arg1) {
  return window['go']['main']['App']['GetAgent'](arg1);
}

export function GetAgentProjects(arg1) {
  return window['go']['main']['App']['GetAgentProjects'](arg1);
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetAllGroups() {
  return window['go']['main']['App']['GetAllGroups']();
}

export function GetAllProjects() {
  return window['go']['main']['App']['GetAllProjects']();
}

export function GetAllUsedPorts() {
  return window['go']['main']['App']['GetAllUsedPorts']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetBusinessUnits(arg1) {
  return window['go']['main']['App']['GetBusinessUnits'](arg1);
}

export function GetCapabilities() {
  return window['go']['main']['App']['GetCapabilities']();
}

export function GetCapabilitiesSummary() {
  return window['go']['main']['App']['GetCapabilitiesSummary']();
}

export function GetChatHistory(arg1) {
  return window['go']['main']['App']['GetChatHistory'](arg1);
}

export function GetClient(arg1) {
  return window['go']['main']['App']['GetClient'](arg1);
}

export function GetClients() {
  return window['go']['main']['App']['GetClients']();
}

export function GetEmail(arg1) {
  return window['go']['main']['App']['GetEmail'](arg1);
}

export function GetEmails(arg1) {
  return window['go']['main']['App']['GetEmails'](arg1);
}

export function GetEnvFileContent(arg1, arg2) {
  return window['go']['main']['App']['GetEnvFileContent'](arg1, arg2);
}

export function GetEnvVariables(arg1, arg2) {
  return window['go']['main']['App']['GetEnvVariables'](arg1, arg2);
}

export function GetEpic(arg1) {
  return window['go']['main']['App']['GetEpic'](arg1);
}

export function GetEpicsByProject(arg1) {
  return window['go']['main']['App']['GetEpicsByProject'](arg1);
}

export function GetGoogleUserInfo() {
  return window['go']['main']['App']['GetGoogleUserInfo']();
}

export function GetIdea(arg1) {
  return window['go']['main']['App']['GetIdea'](arg1);
}

export function GetIdeas(arg1) {
  return window['go']['main']['App']['GetIdeas'](arg1);
}

export function GetInstanceId() {
  return window['go']['main']['App']['GetInstanceId']();
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjectAssignments(arg1) {
  return window['go']['main']['App']['GetProjectAssignments'](arg1);
}

export function GetProjectAssignmentsWithRoles(arg1) {
  return window['go']['main']['App']['GetProjectAssignmentsWithRoles'](arg1);
}

export function GetProjectStats(arg1) {
  return window['go']['main']['App']['GetProjectStats'](arg1);
}

export function GetProjects(arg1, arg2) {
  return window['go']['main']['App']['GetProjects'](arg1, arg2);
}

export function GetRecentActivity(arg1) {
  return window['go']['main']['App']['GetRecentActivity'](arg1);
}

export function GetSubProjectCount(arg1) {
  return window['go']['main']['App']['GetSubProjectCount'](arg1);
}

export function GetSubProjects(arg1) {
  return window['go']['main']['App']['GetSubProjects'](arg1);
}

export function GetSyncState() {
  return window['go']['main']['App']['GetSyncState']();
}

export function GetTasks(arg1, arg2) {
  return window['go']['main']['App']['GetTasks'](arg1, arg2);
}

export function GetTicket(arg1) {
  return window['go']['main']['App']['GetTicket'](arg1);
}

export function GetTicketStats(arg1) {
  return window['go']['main']['App']['GetTicketStats'](arg1);
}

export function GetTicketsByEpic(arg1) {
  return window['go']['main']['App']['GetTicketsByEpic'](arg1);
}

export function GetTicketsByProject(arg1) {
  return window['go']['main']['App']['GetTicketsByProject'](arg1);
}

export function GetTicketsByStatus(arg1, arg2) {
  return window['go']['main']['App']['GetTicketsByStatus'](arg1, arg2);
}

export function GetTodayEvents() {
  return window['go']['main']['App']['GetTodayEvents']();
}

export function GetUpcomingEvents(arg1) {
  return window['go']['main']['App']['GetUpcomingEvents'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsAgentAssigned(arg1, arg2) {
  return window['go']['main']['App']['IsAgentAssigned'](arg1, arg2);
}

export function ListChatSessions() {
  return window['go']['main']['App']['ListChatSessions']();
}

export function LoadSessions() {
  return window['go']['main']['App']['LoadSessions']();
}

export function LogActivity(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['LogActivity'](arg1, arg2, arg3, arg4, arg5);
}

export function LogoutGoogle() {
  return window['go']['main']['App']['LogoutGoogle']();
}

export function MarkAsRead(arg1) {
  return window['go']['main']['App']['MarkAsRead'](arg1);
}

export function MoveProjectToGroup(arg1, arg2) {
  return window['go']['main']['App']['MoveProjectToGroup'](arg1, arg2);
}

export function MoveProjectToStandalone(arg1) {
  return window['go']['main']['App']['MoveProjectToStandalone'](arg1);
}

export function MoveTicket(arg1, arg2) {
  return window['go']['main']['App']['MoveTicket'](arg1, arg2);
}

export function OpenInFinder(arg1) {
  return window['go']['main']['App']['OpenInFinder'](arg1);
}

export function OpenInTerminal(arg1) {
  return window['go']['main']['App']['OpenInTerminal'](arg1);
}

export function PerformHandshake() {
  return window['go']['main']['App']['PerformHandshake']();
}

export function PullLatest(arg1) {
  return window['go']['main']['App']['PullLatest'](arg1);
}

export function RegisterAgent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RegisterAgent'](arg1, arg2, arg3, arg4);
}

export function RemovePort(arg1, arg2) {
  return window['go']['main']['App']['RemovePort'](arg1, arg2);
}

export function ReorderTicket(arg1, arg2) {
  return window['go']['main']['App']['ReorderTicket'](arg1, arg2);
}

export function ResetHandshake() {
  return window['go']['main']['App']['ResetHandshake']();
}

export function SaveEnvFileContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveEnvFileContent'](arg1, arg2, arg3);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function ScanEnvFiles(arg1) {
  return window['go']['main']['App']['ScanEnvFiles'](arg1);
}

export function SearchIdeas(arg1) {
  return window['go']['main']['App']['SearchIdeas'](arg1);
}

export function SearchKnowledge(arg1, arg2) {
  return window['go']['main']['App']['SearchKnowledge'](arg1, arg2);
}

export function SendEmail(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendEmail'](arg1, arg2, arg3);
}

export function SetEnvVariable(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetEnvVariable'](arg1, arg2, arg3, arg4);
}

export function SetLocalPath(arg1, arg2) {
  return window['go']['main']['App']['SetLocalPath'](arg1, arg2);
}

export function StartGoogleLogin() {
  return window['go']['main']['App']['StartGoogleLogin']();
}

export function StartSync() {
  return window['go']['main']['App']['StartSync']();
}

export function StopSync() {
  return window['go']['main']['App']['StopSync']();
}

export function StreamChat(arg1, arg2) {
  return window['go']['main']['App']['StreamChat'](arg1, arg2);
}

export function StreamChatWithImages(arg1, arg2, arg3) {
  return window['go']['main']['App']['StreamChatWithImages'](arg1, arg2, arg3);
}

export function SwitchSession(arg1) {
  return window['go']['main']['App']['SwitchSession'](arg1);
}

export function UnassignAgentFromProject(arg1, arg2) {
  return window['go']['main']['App']['UnassignAgentFromProject'](arg1, arg2);
}

export function UpdateAgentStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateAgentStatus'](arg1, arg2);
}

export function UpdateBusinessUnit(arg1) {
  return window['go']['main']['App']['UpdateBusinessUnit'](arg1);
}

export function UpdateClient(arg1) {
  return window['go']['main']['App']['UpdateClient'](arg1);
}

export function UpdateEpic(arg1) {
  return window['go']['main']['App']['UpdateEpic'](arg1);
}

export function UpdateIdea(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateIdea'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function UpdateIdeaNotes(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateIdeaNotes'](arg1, arg2, arg3, arg4);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function UpdateSuggestedTaskStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSuggestedTaskStatus'](arg1, arg2, arg3);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}

export function UpdateTicket(arg1) {
  return window['go']['main']['App']['UpdateTicket'](arg1);
}
