// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoRepair(arg1) {
  return window['go']['main']['App']['AutoRepair'](arg1);
}

export function CheckGoogleAuth() {
  return window['go']['main']['App']['CheckGoogleAuth']();
}

export function CheckHealth() {
  return window['go']['main']['App']['CheckHealth']();
}

export function ClaimTask(arg1, arg2) {
  return window['go']['main']['App']['ClaimTask'](arg1, arg2);
}

export function ClearChatHistory(arg1) {
  return window['go']['main']['App']['ClearChatHistory'](arg1);
}

export function CreateBusinessUnit(arg1) {
  return window['go']['main']['App']['CreateBusinessUnit'](arg1);
}

export function CreateChatSession(arg1, arg2) {
  return window['go']['main']['App']['CreateChatSession'](arg1, arg2);
}

export function CreateClient(arg1) {
  return window['go']['main']['App']['CreateClient'](arg1);
}

export function CreateEvent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateEvent'](arg1, arg2, arg3, arg4);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteBusinessUnit(arg1) {
  return window['go']['main']['App']['DeleteBusinessUnit'](arg1);
}

export function DeleteClient(arg1) {
  return window['go']['main']['App']['DeleteClient'](arg1);
}

export function DeleteEvent(arg1) {
  return window['go']['main']['App']['DeleteEvent'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetBusinessUnits(arg1) {
  return window['go']['main']['App']['GetBusinessUnits'](arg1);
}

export function GetChatHistory(arg1) {
  return window['go']['main']['App']['GetChatHistory'](arg1);
}

export function GetClient(arg1) {
  return window['go']['main']['App']['GetClient'](arg1);
}

export function GetClients() {
  return window['go']['main']['App']['GetClients']();
}

export function GetEmail(arg1) {
  return window['go']['main']['App']['GetEmail'](arg1);
}

export function GetEmails(arg1) {
  return window['go']['main']['App']['GetEmails'](arg1);
}

export function GetGoogleUserInfo() {
  return window['go']['main']['App']['GetGoogleUserInfo']();
}

export function GetIdeas() {
  return window['go']['main']['App']['GetIdeas']();
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjectStats(arg1) {
  return window['go']['main']['App']['GetProjectStats'](arg1);
}

export function GetProjects(arg1, arg2) {
  return window['go']['main']['App']['GetProjects'](arg1, arg2);
}

export function GetTasks(arg1, arg2) {
  return window['go']['main']['App']['GetTasks'](arg1, arg2);
}

export function GetTodayEvents() {
  return window['go']['main']['App']['GetTodayEvents']();
}

export function GetUpcomingEvents(arg1) {
  return window['go']['main']['App']['GetUpcomingEvents'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListChatSessions() {
  return window['go']['main']['App']['ListChatSessions']();
}

export function LogoutGoogle() {
  return window['go']['main']['App']['LogoutGoogle']();
}

export function MarkAsRead(arg1) {
  return window['go']['main']['App']['MarkAsRead'](arg1);
}

export function SendEmail(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendEmail'](arg1, arg2, arg3);
}

export function StartGoogleLogin() {
  return window['go']['main']['App']['StartGoogleLogin']();
}

export function StreamChat(arg1, arg2) {
  return window['go']['main']['App']['StreamChat'](arg1, arg2);
}

export function StreamChatWithImages(arg1, arg2, arg3) {
  return window['go']['main']['App']['StreamChatWithImages'](arg1, arg2, arg3);
}

export function SwitchSession(arg1) {
  return window['go']['main']['App']['SwitchSession'](arg1);
}

export function UpdateBusinessUnit(arg1) {
  return window['go']['main']['App']['UpdateBusinessUnit'](arg1);
}

export function UpdateClient(arg1) {
  return window['go']['main']['App']['UpdateClient'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}
